require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProjectLogEntriesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProjectLogEntry. As you add validations to ProjectLogEntry, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectLogEntriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all project_log_entries as @project_log_entries" do
      project_log_entry = ProjectLogEntry.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:project_log_entries)).to eq([project_log_entry])
    end
  end

  describe "GET show" do
    it "assigns the requested project_log_entry as @project_log_entry" do
      project_log_entry = ProjectLogEntry.create! valid_attributes
      get :show, {:id => project_log_entry.to_param}, valid_session
      expect(assigns(:project_log_entry)).to eq(project_log_entry)
    end
  end

  describe "GET new" do
    it "assigns a new project_log_entry as @project_log_entry" do
      get :new, {}, valid_session
      expect(assigns(:project_log_entry)).to be_a_new(ProjectLogEntry)
    end
  end

  describe "GET edit" do
    it "assigns the requested project_log_entry as @project_log_entry" do
      project_log_entry = ProjectLogEntry.create! valid_attributes
      get :edit, {:id => project_log_entry.to_param}, valid_session
      expect(assigns(:project_log_entry)).to eq(project_log_entry)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProjectLogEntry" do
        expect {
          post :create, {:project_log_entry => valid_attributes}, valid_session
        }.to change(ProjectLogEntry, :count).by(1)
      end

      it "assigns a newly created project_log_entry as @project_log_entry" do
        post :create, {:project_log_entry => valid_attributes}, valid_session
        expect(assigns(:project_log_entry)).to be_a(ProjectLogEntry)
        expect(assigns(:project_log_entry)).to be_persisted
      end

      it "redirects to the created project_log_entry" do
        post :create, {:project_log_entry => valid_attributes}, valid_session
        expect(response).to redirect_to(ProjectLogEntry.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved project_log_entry as @project_log_entry" do
        post :create, {:project_log_entry => invalid_attributes}, valid_session
        expect(assigns(:project_log_entry)).to be_a_new(ProjectLogEntry)
      end

      it "re-renders the 'new' template" do
        post :create, {:project_log_entry => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_log_entry" do
        project_log_entry = ProjectLogEntry.create! valid_attributes
        put :update, {:id => project_log_entry.to_param, :project_log_entry => new_attributes}, valid_session
        project_log_entry.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested project_log_entry as @project_log_entry" do
        project_log_entry = ProjectLogEntry.create! valid_attributes
        put :update, {:id => project_log_entry.to_param, :project_log_entry => valid_attributes}, valid_session
        expect(assigns(:project_log_entry)).to eq(project_log_entry)
      end

      it "redirects to the project_log_entry" do
        project_log_entry = ProjectLogEntry.create! valid_attributes
        put :update, {:id => project_log_entry.to_param, :project_log_entry => valid_attributes}, valid_session
        expect(response).to redirect_to(project_log_entry)
      end
    end

    describe "with invalid params" do
      it "assigns the project_log_entry as @project_log_entry" do
        project_log_entry = ProjectLogEntry.create! valid_attributes
        put :update, {:id => project_log_entry.to_param, :project_log_entry => invalid_attributes}, valid_session
        expect(assigns(:project_log_entry)).to eq(project_log_entry)
      end

      it "re-renders the 'edit' template" do
        project_log_entry = ProjectLogEntry.create! valid_attributes
        put :update, {:id => project_log_entry.to_param, :project_log_entry => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested project_log_entry" do
      project_log_entry = ProjectLogEntry.create! valid_attributes
      expect {
        delete :destroy, {:id => project_log_entry.to_param}, valid_session
      }.to change(ProjectLogEntry, :count).by(-1)
    end

    it "redirects to the project_log_entries list" do
      project_log_entry = ProjectLogEntry.create! valid_attributes
      delete :destroy, {:id => project_log_entry.to_param}, valid_session
      expect(response).to redirect_to(project_log_entries_url)
    end
  end

end
